
import {
  ArrowLeft, ArrowRight, BarChartBig, Check, ChevronsUpDown, Circle, Copy, CreditCard, Edit, ExternalLink,
  File, HelpCircle, Home, Lightbulb, ListChecks, Loader2, LogIn, LogOut, Mail, Menu, MessageSquare, Moon,
  Plus, PlusCircle, RefreshCw, Repeat, Save, Search, Server, Settings, Share2, Shield, Sun, Trash, User,
  UserPlus, Wand2, Workflow, Twitter, Linkedin, Sparkles, CalendarDays, Send, Feather,
  CheckCircle, Lock, X, AlertTriangle // Added AlertTriangle
} from 'lucide-react';

const Icons = {
  alertTriangle: AlertTriangle, // Added AlertTriangle
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  barChartBig: BarChartBig,
  check: Check,
  checkCircle: CheckCircle,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X, 
  copy: Copy,
  creditCard: CreditCard,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  feather: Feather,
  help: HelpCircle,
  home: Home,
  light: Sun,
  lightbulb: Lightbulb,
  listChecks: ListChecks,
  loader: Loader2,
  logIn: LogIn,
  logOut: LogOut,
  lock: Lock,
  mail: Mail,
  menu: Menu,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  refreshCw: RefreshCw,
  repeat: Repeat,
  save: Save,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  sparkles: Sparkles,
  spinner: Loader2,
  trash: Trash,
  twitter: Twitter,
  user: User,
  userPlus: UserPlus,
  linkedin: Linkedin,
  wand: Wand2,
  calendar: CalendarDays,
};

export {Icons};
