import React from "react";
import { useRouter } from "next/router";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export default function Disclaimer() {
  const router = useRouter();

  const handleSmartNav = (path) => {
    if (router.pathname === path) {
      router.reload();
    } else {
      router.push(path);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#e0e7ff] via-[#c7d2fe] to-[#a5b4fc] py-16 px-4 flex flex-col">
      <div className="max-w-3xl mx-auto bg-white shadow-xl rounded-2xl p-8 sm:p-10 text-gray-800 flex-1">
        {/* Back Button */}
        <Link
          href="/"
          className="flex items-center text-indigo-600 hover:underline mb-6"
        >
          <ArrowLeft className="w-5 h-5 mr-2" /> Back to Home
        </Link>

        <h1 className="text-4xl font-bold mb-6 text-indigo-700">Disclaimer</h1>

        <p className="mb-5">
          <strong>SagePostAI</strong> is an AI-powered tool designed to help
          users generate social media content, campaign ideas, and creative
          marketing text. While we strive to deliver helpful and accurate
          outputs, the content generated is created by artificial intelligence
          and may not always reflect verified facts, personal opinions, or the
          latest trends.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-3 text-indigo-600">
          No Guarantees or Warranties
        </h2>
        <p className="mb-5">
          We do not guarantee that the content generated by SagePostAI will be
          accurate, reliable, error-free, or suitable for all purposes. Users
          are encouraged to review, edit, and verify all AI-generated content
          before using it publicly or professionally.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-3 text-indigo-600">
          User Responsibility
        </h2>
        <p className="mb-5">
          By using SagePostAI, you acknowledge that you are solely responsible
          for the content you generate and share. We are not liable for any
          outcomes resulting from the use or misuse of AI-generated text —
          including but not limited to reputational, legal, or financial
          consequences.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-3 text-indigo-600">
          No Professional Advice
        </h2>
        <p className="mb-5">
          The content generated by SagePostAI is not a substitute for
          professional advice, including legal, financial, or medical guidance.
          Always consult with qualified professionals for decisions in those
          domains.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-3 text-indigo-600">
          Limitation of Liability
        </h2>
        <p className="mb-5">
          Under no circumstances shall SagePostAI, its founders, partners, or
          affiliates be held liable for any damages or losses arising from your
          use of the platform or its outputs.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-3 text-indigo-600">
          Contact Us
        </h2>
        <p>
          If you have questions about this disclaimer, please contact us at{" "}
          <a
            href="mailto:support@sagepostai.com"
            className="text-blue-600 underline"
          >
            support@sagepostai.com
          </a>
          .
        </p>
      </div>

      {/* Footer Legal Links */}
      <div className="border-t pt-6 text-sm text-center text-gray-600 space-x-4 underline">
        <button
          onClick={() => handleSmartNav("/PrivacyPolicy")}
          className="hover:text-indigo-700"
        >
          Privacy Policy
        </button>
        <button
          onClick={() => handleSmartNav("/terms-of-service")}
          className="hover:text-indigo-700"
        >
          Terms of Service
        </button>
        <button
          onClick={() => handleSmartNav("/Refund")}
          className="hover:text-indigo-700"
        >
          Refund Policy
        </button>
        <button
          onClick={() => handleSmartNav("/Cookie-Policy")}
          className="hover:text-indigo-700"
        >
          Cookie Policy
        </button>
        <button
          onClick={() => handleSmartNav("/Disclaimer")}
          className="hover:text-indigo-700"
        >
          Disclaimer
        </button>
        <button
          onClick={() => handleSmartNav("/contact")}
          className="hover:text-indigo-700"
        >
          Contact
        </button>
      </div>
    </div>
  );
}
