
import React from "react";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import Footer from "@/components/sections/Footer";

const PolicySection: React.FC<{title: string, children: React.ReactNode}> = ({ title, children }) => (
  <div className="mb-8">
    <h2 className="text-2xl font-semibold mt-6 mb-3 text-primary">
      {title}
    </h2>
    <div className="space-y-4 text-foreground/80">{children}</div>
  </div>
);

export default function DisclaimerPage() {
  return (
    <div className="text-foreground min-h-screen flex flex-col">
        <main className="flex-grow py-16 sm:py-24 px-4 sm:px-6">
            <div className="max-w-3xl mx-auto">
                <div className="mb-8">
                    <Link href="/" passHref>
                        <Button variant="ghost" className="text-foreground/70 hover:text-foreground">
                            <ArrowLeft className="w-5 h-5 mr-2" />
                            Back to Home
                        </Button>
                    </Link>
                </div>

                <div className="bg-secondary border border-border rounded-lg p-8 sm:p-10">
                    <h1 className="text-3xl font-extrabold mb-6 text-foreground">
                        Disclaimer
                    </h1>
                    <p className="mb-5 text-foreground/80">
                        <strong>SagePostAI</strong> is an AI-powered tool designed to help
                        users generate social media content, campaign ideas, and creative
                        marketing text. While we strive to deliver helpful and accurate
                        outputs, the content generated is created by artificial intelligence
                        and may not always reflect verified facts, personal opinions, or the
                        latest trends.
                    </p>

                    <PolicySection title="No Guarantees or Warranties">
                        <p>
                            We do not guarantee that the content generated by SagePostAI will be
                            accurate, reliable, error-free, or suitable for all purposes. Users
                            are encouraged to review, edit, and verify all AI-generated content
                            before using it publicly or professionally.
                        </p>
                    </PolicySection>
                    
                    <PolicySection title="User Responsibility">
                        <p>
                            By using SagePostAI, you acknowledge that you are solely responsible
                            for the content you generate and share. We are not liable for any
                            outcomes resulting from the use or misuse of AI-generated text —
                            including but not limited to reputational, legal, or financial
                            consequences.
                        </p>
                    </PolicySection>
                    
                    <PolicySection title="No Professional Advice">
                        <p>
                            The content generated by SagePostAI is not a substitute for
                            professional advice, including legal, financial, or medical guidance.
                            Always consult with qualified professionals for decisions in those
                            domains.
                        </p>
                    </PolicySection>

                    <PolicySection title="Limitation of Liability">
                        <p>
                            Under no circumstances shall SagePostAI, its founders, partners, or
                            affiliates be held liable for any damages or losses arising from your
                            use of the platform or its outputs.
                        </p>
                    </PolicySection>

                    <PolicySection title="Contact Us">
                        <p>
                            If you have questions about this disclaimer, please contact us at{" "}
                            <a
                                href="mailto:support@sagepostai.com"
                                className="text-primary underline"
                            >
                                support@sagepostai.com
                            </a>
                            .
                        </p>
                    </PolicySection>
                </div>
            </div>
        </main>
        <Footer/>
    </div>
  );
}
